### ISSUE TITLE
gebuilder

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/NeuroGentooProject#15]
In order to mitigate the BuildServer naming confusion we are splitting the actual "BuildServer" software into a dedicated package: [GeBuilder](https://github.com/IBT-FMI/gebuilder).

Basically emerging this package is what would turn any system into a buildserver. Also, going forward, the installation process should preferentially be handled via Portage rather than working in a cloned repository.

I'll leave ongoing issues here, but future buildserver development should be handled there.

**Comment by Doeme** [comment]
I welcome this, since we loose the stuff unrelated to the buildserver too.
