### ISSUE TITLE
Distributing minimal example

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/NeuroGentooProject#4]
This (or whatever final repository we dedicate to tracking the extra files needed to bring the power of Gentoo to development/top-level/scientific software) should contain a minimal, well-documented, working example of the `.gentoo` standard (ideally with some associated "dummy software").

The documentation text/figures can also be used for your final project presentation, and the upcoming publication. If we start writing bit by bit there will be less confusion and scrambling for time/context/a-red-line at the end.

**Comment by Doeme** [comment]
565af084b3c0671c624e65de5dc9b32863efcb79
